# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc0f8dc463c8444141cd25f7599f95aed660ad8cac7e22d273233f240a35edaf0f448df592d34f84defc71c3f3875c54d1203811b410bdc030e1ed3eeaf38209

test:
  secret_key_base: 3c046f13061565dc476a20bc5af0f503594d766e700f5573ee928be8985a221904bcbbbcaceac6905fe8f9658acaca6dba2409fc1a03e17615e8b6f99564881b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
